/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AvatarAvatar: typeof import('./components/Avatar/Avatar.vue')['default']
    AvatarStackedAvatars: typeof import('./components/Avatar/StackedAvatars.vue')['default']
    AvatarStackedAvatarsCounter: typeof import('./components/Avatar/StackedAvatarsCounter.vue')['default']
    BreadcrumbBreadcrumb: typeof import('./components/Breadcrumb/Breadcrumb.vue')['default']
    BreadcrumbBreadcrumbItem: typeof import('./components/Breadcrumb/BreadcrumbItem.vue')['default']
    ButtonButton: typeof import('./components/Button/Button.vue')['default']
    CheckboxCheckbox: typeof import('./components/Checkbox/Checkbox.vue')['default']
    DropdownDropdown: typeof import('./components/Dropdown/Dropdown.vue')['default']
    FormCompleteRegistration: typeof import('./components/FormCompleteRegistration.vue')['default']
    FormDeleteUser: typeof import('./components/FormDeleteUser.vue')['default']
    FormUser: typeof import('./components/FormUser.vue')['default']
    InputCounter: typeof import('./components/InputCounter.vue')['default']
    InputInput: typeof import('./components/Input/Input.vue')['default']
    LoginForm: typeof import('./components/LoginForm.vue')['default']
    ModalisModal: typeof import('./components/Modalis/Modal.vue')['default']
    ModalModal: typeof import('./components/Modal/Modal.vue')['default']
    PasswordStrength: typeof import('./components/PasswordStrength.vue')['default']
    ProfileDropdown: typeof import('./components/ProfileDropdown.vue')['default']
    ReservationsCalendarMonth: typeof import('./components/Reservations/CalendarMonth.vue')['default']
    ReservationsCalendarMonthCopy: typeof import('./components/Reservations/CalendarMonth-copy.vue')['default']
    ReservationsDatesAndGuests: typeof import('./components/Reservations/DatesAndGuests.vue')['default']
    ReservationsEventDetailsModal: typeof import('./components/Reservations/EventDetailsModal.vue')['default']
    ReservationsFormReservation: typeof import('./components/Reservations/FormReservation.vue')['default']
    ReservationsFullCalendar: typeof import('./components/Reservations/FullCalendar.vue')['default']
    ReservationsGuestsCounters: typeof import('./components/Reservations/GuestsCounters.vue')['default']
    ReservationsReservationDates: typeof import('./components/Reservations/ReservationDates.vue')['default']
    ReservationsReservationDatesCopy: typeof import('./components/Reservations/ReservationDates-copy.vue')['default']
    ReservationsReservationForm: typeof import('./components/Reservations/ReservationForm.vue')['default']
    ReservationsStepCompletedIcon: typeof import('./components/Reservations/StepCompletedIcon.vue')['default']
    SelectSelect: typeof import('./components/Select/Select.vue')['default']
    SpinnerSpinner: typeof import('./components/Spinner/Spinner.vue')['default']
    UserCard: typeof import('./components/UserCard.vue')['default']
    UserItemList: typeof import('./components/UserItemList.vue')['default']
    UserList: typeof import('./components/UserList.vue')['default']
    UserSettings: typeof import('./components/UserSettings.vue')['default']
    UtilsFlowbiteThemableComponentsFlowbiteThemableChildFlowbiteThemableChild: typeof import('./components/utils/FlowbiteThemable/components/FlowbiteThemableChild/FlowbiteThemableChild.vue')['default']
    UtilsFlowbiteThemableFlowbiteThemable: typeof import('./components/utils/FlowbiteThemable/FlowbiteThemable.vue')['default']
    UtilsSlotListenerSlotListener: typeof import('./components/utils/SlotListener/SlotListener.vue')['default']
  }
}
