/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AvailabilityCalendar: typeof import('./src/components/common/AvailabilityCalendar.vue')['default']
    ClearButton: typeof import('./src/components/common/ClearButton.vue')['default']
    ContactForm: typeof import('./src/components/common/ContactForm.vue')['default']
    CreditCard: typeof import('./src/components/PaymentForm/CreditCard.vue')['default']
    DatesAndGuests: typeof import('./src/components/ReservationForm/DatesAndGuests.vue')['default']
    DatesAndGuestsQuickForm: typeof import('./src/components/ReservationForm/DatesAndGuestsQuickForm.vue')['default']
    DropdownContent: typeof import('./src/components/common/DropdownContent.vue')['default']
    EventDetailsModal: typeof import('./src/components/common/EventDetailsModal.vue')['default']
    GuestsCounters: typeof import('./src/components/ReservationForm/GuestsCounters.vue')['default']
    InputCounter: typeof import('./src/components/common/InputCounter.vue')['default']
    PaymentForm: typeof import('./src/components/PaymentForm/PaymentForm.vue')['default']
    ReservationConfirmation: typeof import('./src/components/ReservationForm/ReservationConfirmation.vue')['default']
    ReservationForm: typeof import('./src/components/ReservationForm/ReservationForm.vue')['default']
    ReservationFormFooter: typeof import('./src/components/ReservationForm/ReservationFormFooter.vue')['default']
    ReservationFormHeader: typeof import('./src/components/ReservationForm/ReservationFormHeader.vue')['default']
    ReservationPayment: typeof import('./src/components/ReservationForm/ReservationPayment.vue')['default']
    ReservationSuccess: typeof import('./src/components/ReservationForm/ReservationSuccess.vue')['default']
    RiAddLine: typeof import('~icons/ri/add-line')['default']
    RiArrowDownSFill: typeof import('~icons/ri/arrow-down-s-fill')['default']
    RiArrowRightLine: typeof import('~icons/ri/arrow-right-line')['default']
    RiCloseLine: typeof import('~icons/ri/close-line')['default']
    RiMoonClearFill: typeof import('~icons/ri/moon-clear-fill')['default']
    RiSubtractLine: typeof import('~icons/ri/subtract-line')['default']
    RiSunFill: typeof import('~icons/ri/sun-fill')['default']
    StepCompletedIcon: typeof import('./src/components/ReservationForm/StepCompletedIcon.vue')['default']
    ToggleTheme: typeof import('./src/components/common/ToggleTheme.vue')['default']
  }
}
