/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Calendar: typeof import('./src/components/common/Calendar.vue')['default']
    ClearButton: typeof import('./src/components/common/ClearButton.vue')['default']
    Confirmation: typeof import('./src/components/ReservationForm/Confirmation.vue')['default']
    Counter: typeof import('./src/components/common/Counter.vue')['default']
    CreditCard: typeof import('./src/components/PaymentForm/CreditCard.vue')['default']
    DatesAndGuests: typeof import('./src/components/ReservationForm/DatesAndGuests.vue')['default']
    DatesAndGuestsQuickForm: typeof import('./src/components/ReservationForm/DatesAndGuestsQuickForm.vue')['default']
    Dropdown: typeof import('./src/components/common/Dropdown.vue')['default']
    DropdownContent: typeof import('./src/components/common/DropdownContent.vue')['default']
    EventDetailsModal: typeof import('./src/components/common/EventDetailsModal.vue')['default']
    GuestsCounters: typeof import('./src/components/ReservationForm/GuestsCounters.vue')['default']
    Payment: typeof import('./src/components/ReservationForm/Payment.vue')['default']
    PaymentForm: typeof import('./src/components/PaymentForm/PaymentForm.vue')['default']
    ReservationForm: typeof import('./src/components/ReservationForm/ReservationForm.vue')['default']
    ReservationFormFooter: typeof import('./src/components/ReservationForm/ReservationFormFooter.vue')['default']
    ReservationFormHeader: typeof import('./src/components/ReservationForm/ReservationFormHeader.vue')['default']
    RiAddLine: typeof import('~icons/ri/add-line')['default']
    RiArrowDownSFill: typeof import('~icons/ri/arrow-down-s-fill')['default']
    RiArrowRightLine: typeof import('~icons/ri/arrow-right-line')['default']
    RiCloseLine: typeof import('~icons/ri/close-line')['default']
    RiSubtractLine: typeof import('~icons/ri/subtract-line')['default']
    Success: typeof import('./src/components/ReservationForm/Success.vue')['default']
  }
}
