import Vue from '@vitejs/plugin-vue';
import { resolve } from 'node:path';
import IconsResolver from 'unplugin-icons/resolver';
import Icons from 'unplugin-icons/vite';
import Components from 'unplugin-vue-components/vite';
import { defineConfig } from 'vite';
import * as pkg from './package.json';

const externals = [...Object.keys(pkg.dependencies || {}), ...Object.keys(pkg.peerDependencies || {})];

const port = parseInt(process.env.PORT || '') || 3309;
const r = (...args) => resolve(__dirname, ...args);

export default defineConfig(({ command }) => {
  const isDev = command === 'serve';

  return {
    base: isDev ? `http://localhost:${port}/` : undefined,

    server: {
      port,
      hmr: {
        host: 'localhost',
      },
    },

    plugins: [
      Vue({ style: { filename: `style.css` } }), // to process SFC

      Components({
        dirs: [r('src/components')],
        // auto import icons
        resolvers: [
          IconsResolver({
            prefix: '',
          }),
        ],
      }),

      Icons({ autoInstall: true, compiler: 'vue3' }),
    ],

    build: {
      minify: false,
      sourcemap: false,
      // Output compiled files to /dist.
      outDir: `./dist`,
      emptyOutDir: false, // to retain the types folder generated by tsc
      sourcemap: isDev ? 'inline' : false,
      lib: {
        // Set the entry point (file that contains our components exported).
        entry: resolve(__dirname, `src/index.ts`),
        // Name of the library.
        name: `kalmiawoods-ui-vue`,
        // We are building for CJS and ESM, use a function to rename automatically files.
        // Example: my-component-library.esm.js
        fileName: (format) => `kalmiawoods-ui-vue.${format}.js`,
      },
      rollupOptions: {
        // Vue is provided by the parent project, don't compile Vue source-code inside our library.
        external: externals,
        output: {
          // disable warning on src/index.ts using both default and named export
          exports: 'named',
          // Provide global variables to use in the UMD build
          // for externalized deps (not useful if 'umd' is not in lib.formats)
          globals: {
            vue: `Vue`,
            '@vueuse/core': 'vue-use',
            'v-calendar': 'v-calendar',
          },
        },
      },
    },

    optimizeDeps: {
      include: ['vue', '@vueuse/core', 'v-calendar'],
    },

    resolve: {
      alias: {
        // Alias src directory for @/components/{KongponentName} imports
        '@': r('./src/'),
        // This just ensures the style import isn't impacted by the separate v-calendar alias below
        // 'v-calendar/dist/style.css': r('../node_modules/v-calendar/dist/style.css'),
        // We must alias `v-calendar` here for the docs build to specifically utilize the esm build
        // 'v-calendar': r('../node_modules/v-calendar/dist/v-calendar.es.js'),
        // We must alias `date-fns-tz` here for the docs build to specifically utilize the esm build
        // 'date-fns-tz': r('../node_modules/date-fns-tz/esm'),
      },
    },
  };
});
