/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppleAddToHomeScreenModal: typeof import('./components/AppleAddToHomeScreenModal.vue')['default']
    KwButton: typeof import('./components/KwButton.vue')['default']
    KwCheckboxGroup: typeof import('./components/KwCheckboxGroup.vue')['default']
    KwDatePicker: typeof import('./components/KwDatePicker.vue')['default']
    KwForm: typeof import('./components/KwForm.vue')['default']
    KwSelectField: typeof import('./components/KwSelectField.vue')['default']
    KwSpinner: typeof import('./components/KwSpinner.vue')['default']
    KwTextField: typeof import('./components/KwTextField.vue')['default']
    Logo: typeof import('./components/Logo.vue')['default']
    LogoutButton: typeof import('./components/LogoutButton.vue')['default']
    PasswordStrength: typeof import('./components/PasswordStrength.vue')['default']
    PictureUploader: typeof import('./components/PictureUploader.vue')['default']
    ProfileDropdownUser: typeof import('./components/ProfileDropdownUser.vue')['default']
    SvgSpriteVue: typeof import('./components/SvgSpriteVue.vue')['default']
    UserAvatar: typeof import('./components/UserAvatar.vue')['default']
    UserAvatarCurrentUser: typeof import('./components/UserAvatarCurrentUser.vue')['default']
  }
}
